-- Polymarket leagues reference export
CREATE TABLE IF NOT EXISTS polymarket_leagues_reference (
    league_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    alternate_name TEXT NOT NULL,
    sport TEXT NOT NULL,
    association TEXT NOT NULL
);

DELETE FROM polymarket_leagues_reference;
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (1, 'NCAAB', 'ncaab', 'basketball', 'ncaa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (2, 'Premier League', 'epl', 'soccer', 'premierleague.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (3, 'LaLiga', 'lal', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (95, 'ACN', 'acn', '', 'cafonline.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (5, 'Indian Premier League', 'ipl', 'cricket', 'iplt20.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (6, 'Women''s National Basketball Association', 'wnba', 'basketball', 'wnba.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (7, 'Bundesliga', 'bun', 'soccer', 'bundesliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (8, 'Major League Baseball', 'mlb', 'baseball', 'mlb.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (9, 'CFB', 'cfb', 'american_football', 'ncaa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (10, 'National Football League', 'nfl', 'american_football', 'nfl.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (11, 'Ligue 1', 'fl1', 'soccer', 'ligue1.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (12, 'Serie A', 'sea', 'soccer', 'legaseriea.it');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (13, 'UEFA Champions League', 'ucl', 'soccer', 'uefa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (15, 'AFC', 'afc', '', 'the-afc.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (16, 'OFC', 'ofc', '', 'oceaniafootball.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (17, 'FIF', 'fif', 'soccer', 'fifa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (18, 'ERE', 'ere', '', 'eredivisie.eu');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (19, 'ARG', 'arg', '', 'afa.com.ar');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (20, 'ITC', 'itc', 'soccer', 'legaseriea.it');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (21, 'MEX', 'mex', '', 'ligamx.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (22, 'LCS', 'lcs', '', 'leaguescup.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (23, 'LIB', 'lib', '', 'conmebollibertadores.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (24, 'SUD', 'sud', '', 'conmebolsudamericana.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (25, 'TUR', 'tur', '', 'tff.org');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (26, 'CON', 'con', '', 'conmebol.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (27, 'COF', 'cof', '', 'concacaf.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (28, 'UEF', 'uef', 'soccer', 'uefa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (29, 'CAF', 'caf', '', 'cafonline.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (30, 'RUS', 'rus', '', 'premierliga.ru');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (31, 'EFA', 'efa', '', 'thefa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (32, 'EFL', 'efl', '', 'efl.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (34, 'National Basketball Association', 'nba', 'basketball', 'nba.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (35, 'NHL', 'nhl', '', 'nhl.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (36, 'UEL', 'uel', 'soccer', 'uefa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (38, 'DOTA2', 'dota2', 'esports', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (39, 'LOL', 'lol', 'esports', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (41, 'ODI', 'odi', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (42, 'T20', 't20', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (43, 'ABB', 'abb', '', 'bigbash.com.au');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (44, 'CSA', 'csa', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (45, 'ATP Tour', 'atp', 'tennis', 'atptour.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (46, 'WTA Tour', 'wta', 'tennis', 'wtatennis.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (33, 'MLS', 'mls', '', 'mls.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (40, 'VAL', 'val', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (37, 'CS2', 'cs2', '', 'hltv.org');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (47, 'CWBB', 'cwbb', 'basketball', 'ncaa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (148, 'WBC', 'wbc', 'baseball', 'mlb.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (49, 'CDR', 'cdr', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (50, 'MLBB', 'mlbb', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (51, 'OW', 'ow', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (96, 'CRBAN', 'crban', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (53, 'CODMW', 'codmw', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (54, 'FIFA', 'fifa', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (98, 'RUTOPFT', 'rutopft', '', 'lnr.fr');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (56, 'PUBG', 'pubg', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (57, 'R6SIEGE', 'r6siege', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (58, 'RL', 'rl', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (101, 'BKLIGEND', 'bkligend', '', 'acb.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (103, 'BKNBL', 'bknbl', '', 'nbl.com.au');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (61, 'COL', 'col', 'soccer', 'uefa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (62, 'CDE', 'cde', '', 'fff.fr');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (63, 'DFB', 'dfb', '', 'dfb.de');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (64, 'BRA', 'bra', '', 'cbf.com.br');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (65, 'JAP', 'jap', '', 'jleague.jp');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (66, 'JA2', 'ja2', '', 'jleague.jp');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (67, 'KOR', 'kor', '', 'kleague.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (68, 'SPL', 'spl', '', 'spl.com.sa');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (69, 'CHI', 'chi', '', 'cfa.com.cn');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (70, 'AUS', 'aus', '', 'aleague.com.au');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (71, 'IND', 'ind', '', 'indiansuperleague.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (72, 'NOR', 'nor', '', 'eliteserien.no');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (73, 'DEN', 'den', '', 'superliga.dk');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (74, 'POR', 'por', '', 'ligaportugal.pt');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (75, 'TEST', 'test', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (76, 'SHE', 'she', '', 'cricket.com.au');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (77, 'SASA', 'sasa', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (78, 'LPL', 'lpl', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (79, 'PSP', 'psp', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (80, 'KBO', 'kbo', '', 'koreabaseball.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (81, 'SHL', 'shl', '', 'eliteprospects.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (82, 'CEHL', 'cehl', '', 'hokej.cz');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (83, 'DEHL', 'dehl', '', 'penny-del.org');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (84, 'SNHL', 'snhl', '', 'nationalleague.ch');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (85, 'KHL', 'khl', '', 'en.khl.ru');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (48, 'UFC', 'ufc', '', 'ufc.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (86, 'AHL', 'ahl', '', 'theahl.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (87, 'CRINT', 'crint', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (4, 'CBB', 'cbb', 'basketball', 'ncaa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (91, 'CRAUS', 'craus', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (89, 'CRENG', 'creng', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (94, 'CRNEW', 'crnew', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (88, 'CRIND', 'crind', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (92, 'CRSOU', 'crsou', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (90, 'CRPAK', 'crpak', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (93, 'CRUAE', 'cruae', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (52, 'HOK', 'hok', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (55, 'WILDRIFT', 'wildrift', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (59, 'SC2', 'sc2', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (60, 'SC', 'sc', '', 'liquipedia.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (97, 'RUPREM', 'ruprem', '', 'premiershiprugby.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (99, 'SSC', 'ssc', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (100, 'BKCL', 'bkcl', '', 'championsleague.basketball');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (102, 'BKSERIEA', 'bkseriea', '', 'flashscoreusa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (104, 'BKCBA', 'bkcba', '', 'flashscore.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (105, 'BKFR1', 'bkfr1', '', 'lnb.fr');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (106, 'BKARG', 'bkarg', 'basketball', 'lnba.com.ar');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (107, 'BKKBL', 'bkkbl', '', 'kbl.or.kr');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (108, 'RUSIXNAT', 'rusixnat', '', 'sixnationsrugby.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (109, 'RUEUCHAMP', 'rueuchamp', '', 'epcrugby.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (110, 'RUURC', 'ruurc', '', 'unitedrugby.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (111, 'RUSRP', 'rusrp', '', 'super.rugby');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (112, 'RUCHAMP', 'ruchamp', '', 'sarugby.co.za');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (113, 'CRU19WC', 'cru19wc', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (114, 'CRWPL20', 'crwpl20', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (115, 'CRWNCL', 'crwncl', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (116, 'CRWT20WCGQ', 'crwt20wcgq', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (117, 'CRAFGWI20', 'crafgwi20', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (118, 'CRBTNMLYHKG20', 'crbtnmlyhkg20', '', 'icc-cricket.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (119, 'ZUFFA', 'zuffa', '', 'ufc.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (120, 'MAR1', 'mar1', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (121, 'EGY1', 'egy1', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (122, 'CZE1', 'cze1', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (123, 'BOL1', 'bol1', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (124, 'ROU1', 'rou1', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (130, 'MWOH', 'mwoh', '', 'olympics.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (125, 'BRA2', 'bra2', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (126, 'PER1', 'per1', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (132, 'EUROLEAGUE', 'euroleague', '', 'euroleaguebasketball.net');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (131, 'WWOH', 'wwoh', '', 'olympics.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (133, 'WTTMEN', 'wttmen', '', 'worldtabletennis.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (134, 'CRICIPL', 'cricipl', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (136, 'CRICPSL', 'cricpsl', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (138, 'CRICCPL', 'criccpl', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (140, 'CRICSM', 'cricsm', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (142, 'CRICSA20', 'cricsa20', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (144, 'CRICT20PLW', 'crict20plw', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (146, 'CRICCSAT20W', 'criccsat20w', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (147, 'CRICWNCL', 'cricwncl', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (149, 'UWCL', 'uwcl', 'soccer', 'uefa.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (151, 'PLL', 'pll', '', 'premierlacrosseleague.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (153, 'CRICSS', 'cricss', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (156, 'CRICHKT20W', 'crichkt20w', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (157, 'J2-100', 'j2-100', '', 'jleague.jp');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (159, 'CRICLCL', 'criclcl', '', 'llct20.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (162, 'CHESS', 'chess', '', 'lichess.org');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (163, 'BKVTB', 'bkvtb', '', 'vtb-league.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (164, 'BKBBL', 'bkbbl', '', 'easycredit-bbl.de');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (165, 'BKABA', 'bkaba', '', 'aba-liga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (166, 'BKBSL', 'bkbsl', '', 'tbl.org.tr');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (167, 'BKGR1', 'bkgr1', '', 'esake.gr');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (168, 'BKJPN', 'bkjpn', '', 'bleague.jp');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (169, 'BKFIBAQAF', 'bkfibaqaf', '', 'fiba.basketball');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (170, 'BKFIBAQAM', 'bkfibaqam', '', 'fiba.basketball');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (171, 'BKFIBAQAS', 'bkfibaqas', '', 'fiba.basketball');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (172, 'BKFIBAQEU', 'bkfibaqeu', '', 'fiba.basketball');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (127, 'COL1', 'col1', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (135, 'CRICBBL', 'cricbbl', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (137, 'CRICT20BLAST', 'crict20blast', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (139, 'CRICBPL', 'cricbpl', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (141, 'CRICT20LPL', 'crict20lpl', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (143, 'CRICILT20', 'cricilt20', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (145, 'CRICMLC', 'cricmlc', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (150, 'UKR1', 'ukr1', '', 'upl.ua');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (152, 'WLL', 'wll', '', 'thewll.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (154, 'CRICPAKT20CUP', 'cricpakt20cup', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (158, 'J1-100', 'j1-100', '', 'jleague.jp');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (160, 'CRICNT20C', 'cricnt20c', '', 'espncricinfo.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (161, 'CRICTHUNDERBOLT', 'cricthunderbolt', '', 'ipl.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (128, 'CHI1', 'chi1', 'soccer', 'laliga.com');
INSERT INTO polymarket_leagues_reference (league_id, name, alternate_name, sport, association) VALUES (155, 'CRICPS', 'cricps', '', 'espncricinfo.com');
